name: Generate Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate github-metrics.svg
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Pengaturan Zona Waktu
          config_timezone: Asia/Jakarta
          
          # Solusi agar tidak terpotong (menambah ruang bawah)
          config_padding: 0, 8 + 12%
          
          # Menampilkan data inti dan menyembunyikan metrik bernilai 0 / NaN
          base: header, activity, community
          base_indepth: yes
          
          # Kalender Isometrik 3D
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Commit otomatis
          output_action: commit
          committer_message: "chore: fix and update metrics layout"
